// Renders metrics.csv as a Markdown table into RESULTS.md, between the
// monitor markers (a new section is appended if they are missing).
import { readFile, writeFile } from 'node:fs/promises';
import { config } from './config.ts';
import { parseCsv, renderTable, replaceSection } from './format.ts';

const rows = parseCsv(await readFile(config.csvFile, 'utf8'));
if (rows.length === 0) {
  console.error(`${config.csvFile} has no samples yet`);
  process.exit(1);
}

const first = rows[0].timestamp;
const last = rows[rows.length - 1].timestamp;
const body = [
  `${rows.length} sample(s) from ${first} to ${last}, generated by \`cd monitor && npm run report\`. ` +
    'Latency and error counts are from the simulator’s latest 10-second window at each sample. ' +
    'Query times are wall-clock times for the city-wide panel’s SQL, including fetching the rows.',
  '',
  renderTable(rows),
].join('\n');

const doc = await readFile(config.resultsFile, 'utf8');
await writeFile(config.resultsFile, replaceSection(doc, body));
console.log(`wrote ${rows.length} row(s) to ${config.resultsFile}`);
