// npm run timeline -- <simulator.log> [--restored <ISO time>] [--section <name>]
//
// Prints a summary of a simulator log as Markdown. With --section, writes it
// into RESULTS.md between <!-- name:start --> and <!-- name:end --> instead.
import { readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { parseArgs } from 'node:util';
import { config } from './config.ts';
import { replaceSection } from './format.ts';
import { parseLog, summarize } from './timeline.ts';

const { values, positionals } = parseArgs({
  allowPositionals: true,
  options: { restored: { type: 'string' }, section: { type: 'string' } },
});
if (positionals.length !== 1) {
  console.error('usage: npm run timeline -- <simulator.log> [--restored <ISO time>] [--section <name>]');
  process.exit(2);
}

// npm sets INIT_CWD to the directory npm was run from, so relative log paths
// work the way you typed them.
const logPath = resolve(process.env.INIT_CWD ?? process.cwd(), positionals[0]);
const raw = await readFile(logPath);
// PowerShell 5.1's Tee-Object and ">" write UTF-16LE with a BOM.
const text = (raw[0] === 0xff && raw[1] === 0xfe ? raw.subarray(2).toString('utf16le') : raw.toString('utf8')).replace(/^\uFEFF/, '');

let restoredAt: number | undefined;
if (values.restored !== undefined) {
  restoredAt = Date.parse(values.restored);
  if (Number.isNaN(restoredAt)) {
    console.error(`--restored must be an ISO time such as 2026-09-30T14:05:00Z, got "${values.restored}"`);
    process.exit(2);
  }
}

const summary = summarize(parseLog(text), { restoredAt });
if (values.section) {
  const body = `Generated by \`npm run timeline\` from \`${positionals[0]}\`.\n\n${summary}`;
  const doc = await readFile(config.resultsFile, 'utf8');
  await writeFile(config.resultsFile, replaceSection(doc, body, values.section, values.section));
  console.log(`wrote the ${values.section} section of ${config.resultsFile}`);
} else console.log(summary);
